"""Tests for carmel.services.reextraction: append-only re-extraction of a stored artifact.

All fixtures are SYNTHETIC: hand-built minimal PDFs (no real paper text ever enters
this repo), following the same hand-built-PDF approach as
``tests/test_extract.py::_build_tiny_pdf`` -- no dependency on a PDF-writing library,
only on ``pypdf`` to parse them.
"""

from __future__ import annotations

import hashlib
import json
import sys
import types
from datetime import UTC, datetime
from pathlib import Path

import pytest

import carmel.services.reextraction as reextraction_module
from carmel.agents.tools.extract import ExtractedText, PageExtractionFailure
from carmel.agents.tools.fetch import FetchedArtifact
from carmel.schemas.literature import ArtifactProvenance
from carmel.services.evidence import artifact_dir, store_artifact
from carmel.services.extraction_record import extraction_record_dir, list_extraction_records
from carmel.services.reextraction import ReextractionError, reextract_artifact

MAX_BYTES = 10_000_000


def _build_tiny_pdf(text: bytes) -> bytes:
    """Build a minimal, syntactically valid single-page PDF containing ``text``.

    Copied from ``tests/test_extract.py::_build_tiny_pdf`` (hand-built rather than
    generated by a PDF library, so this fixture has no dependency on pypdf being
    installed to CREATE it -- only to parse it, which is what's under test).
    """
    content_stream = f"BT /F1 24 Tf 72 700 Td ({text.decode('utf-8')}) Tj ET".encode()
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> "
        b"/MediaBox [0 0 612 792] /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(content_stream)).encode() + b" >>\nstream\n" + content_stream + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref_offset = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF".encode()
    return bytes(out)


def _build_empty_text_pdf() -> bytes:
    """A minimal, syntactically valid single-page PDF whose content stream draws
    nothing, so a real pypdf parse succeeds cleanly (no exception, no page
    failure) but yields empty extracted text -- the "clean but empty" case for
    step 9's empty-text refusal, as opposed to a parse-failure case."""
    content_stream = b"BT ET"
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> "
        b"/MediaBox [0 0 612 792] /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(content_stream)).encode() + b" >>\nstream\n" + content_stream + b"\nendstream",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets = []
    for i, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + obj + b"\nendobj\n"
    xref_offset = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF".encode()
    return bytes(out)


def _fetched_artifact(
    data: bytes, *, url: str = "https://example.org/paper.pdf", content_type: str = "application/pdf"
) -> FetchedArtifact:
    return FetchedArtifact(
        url=url,
        final_url=url,
        sha256=hashlib.sha256(data).hexdigest(),
        content_type=content_type,
        n_bytes=len(data),
        fetched_at=datetime.now(UTC),
    )


def _stale_extracted(text: str = "OLD STALE ROOT TEXT") -> ExtractedText:
    """A synthetic ExtractedText deliberately DECOUPLED from any real PDF bytes --
    stands in for an older extractor's output, so tests can force root/raw
    divergence without needing two different real extractors installed."""
    return ExtractedText(text=text, normalized=text.casefold(), sections=[], extractor="pdf:pypdf", lossy=False)


def _store_synthetic_artifact(
    tmp_path: Path,
    data: bytes,
    *,
    content_type: str = "application/pdf",
    root_extracted: ExtractedText | None = None,
) -> str:
    """Store a synthetic root artifact and return its raw_sha256.

    ``root_extracted`` lets a test control exactly what the ROOT ``extracted.json``
    says, independent of ``data`` -- this is how the divergence tests force root and
    raw bytes to disagree without touching ``reextraction.py``'s own write path.
    """
    artifact = _fetched_artifact(data, content_type=content_type)
    extracted = root_extracted if root_extracted is not None else _stale_extracted()
    stored = store_artifact(
        tmp_path,
        data=data,
        artifact=artifact,
        extracted=extracted,
        provenance=ArtifactProvenance.MANUAL,
        max_bytes=MAX_BYTES,
    )
    return stored.sha256


def _root_files(tmp_path: Path, raw_sha256: str) -> dict[str, bytes]:
    d = artifact_dir(tmp_path, raw_sha256)
    return {
        "raw.bin": (d / "raw.bin").read_bytes(),
        "text.txt": (d / "text.txt").read_bytes(),
        "extracted.json": (d / "extracted.json").read_bytes(),
        "meta.json": (d / "meta.json").read_bytes(),
    }


def _extraction_text(tmp_path: Path, raw_sha256: str, extraction_sha256: str) -> str:
    record_dir = extraction_record_dir(tmp_path, raw_sha256, extraction_sha256)
    payload = json.loads((record_dir / "extracted.json").read_bytes())
    return payload["text"]


class TestFreshBytesNotStaleRootSidecar:
    def test_reextraction_uses_fresh_bytes_not_the_stale_root_sidecar(self, tmp_path: Path) -> None:
        """The single most important property of this module: the persisted
        extraction record must reflect a genuine re-parse of raw.bin, never a
        mirror of the (deliberately stale) root extracted.json."""
        pdf_bytes = _build_tiny_pdf(b"Hello Fresh")
        raw_sha256 = _store_synthetic_artifact(
            tmp_path, pdf_bytes, root_extracted=_stale_extracted("OLD STALE ROOT TEXT")
        )

        extraction_sha256 = reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

        fresh_text = _extraction_text(tmp_path, raw_sha256, extraction_sha256)
        assert "Hello Fresh" in fresh_text
        assert "OLD STALE ROOT TEXT" not in fresh_text


class TestRootImmutability:
    def test_root_files_are_byte_identical_before_and_after(self, tmp_path: Path) -> None:
        pdf_bytes = _build_tiny_pdf(b"Immutable Root Check")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)
        before = _root_files(tmp_path, raw_sha256)

        reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

        after = _root_files(tmp_path, raw_sha256)
        assert before == after


class TestIdempotence:
    def test_repeated_reextraction_returns_the_same_address_without_raising(self, tmp_path: Path) -> None:
        pdf_bytes = _build_tiny_pdf(b"Idempotent Content")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)

        first = reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)
        second = reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

        assert first == second
        records = list_extraction_records(tmp_path, raw_sha256)
        assert len(records) == 1


class TestDeliberateRootRecordDivergence:
    def test_root_and_nested_record_deliberately_disagree_after_reextraction(self, tmp_path: Path) -> None:
        """Documents, explicitly, that nothing reconciles the root sidecar with the
        new extraction record -- the root is left describing the OLD extraction on
        purpose. This is intentional (see the module docstring on reextraction.py),
        not a bug for a future reader to "fix" by writing the fresh text back onto
        the root files."""
        pdf_bytes = _build_tiny_pdf(b"Divergent Fresh Text")
        raw_sha256 = _store_synthetic_artifact(
            tmp_path, pdf_bytes, root_extracted=_stale_extracted("Divergent Stale Text")
        )

        extraction_sha256 = reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

        root_text = (artifact_dir(tmp_path, raw_sha256) / "text.txt").read_text(encoding="utf-8")
        record_text = _extraction_text(tmp_path, raw_sha256, extraction_sha256)
        assert root_text == "Divergent Stale Text"
        assert "Divergent Fresh Text" in record_text
        assert root_text != record_text


class TestRefusals:
    def test_step1_rejects_malformed_raw_sha256(self, tmp_path: Path) -> None:
        with pytest.raises(ReextractionError, match=r"well-formed 64-character lowercase hex digest"):
            reextract_artifact(tmp_path, raw_sha256="not-a-digest", max_bytes=MAX_BYTES)

    def test_step1_rejects_uppercase_hex(self, tmp_path: Path) -> None:
        with pytest.raises(ReextractionError, match=r"well-formed 64-character lowercase hex digest"):
            reextract_artifact(tmp_path, raw_sha256="A" * 64, max_bytes=MAX_BYTES)

    def test_step3_refuses_when_raw_bin_is_missing(self, tmp_path: Path) -> None:
        raw_sha256 = "b" * 64
        with pytest.raises(ReextractionError, match=r"raw\.bin does not exist"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step4_refuses_when_on_disk_size_exceeds_max_bytes(self, tmp_path: Path) -> None:
        pdf_bytes = _build_tiny_pdf(b"Too Big For The Cap")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)
        with pytest.raises(ReextractionError, match=r"exceeds max_bytes cap"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=len(pdf_bytes) - 1)

    def test_step5_refuses_when_raw_bin_no_longer_hashes_to_its_own_directory_name(self, tmp_path: Path) -> None:
        pdf_bytes = _build_tiny_pdf(b"Original Content")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)
        tampered = _build_tiny_pdf(b"Tampered Content Post-Store")
        (artifact_dir(tmp_path, raw_sha256) / "raw.bin").write_bytes(tampered)

        with pytest.raises(ReextractionError, match=r"does not hash to its own directory name"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step6_refuses_bytes_that_do_not_sniff_as_pdf(self, tmp_path: Path) -> None:
        data = b"this is definitely not a pdf file"
        raw_sha256 = _store_synthetic_artifact(tmp_path, data, content_type="application/pdf")

        with pytest.raises(ReextractionError, match=r"does not sniff as a PDF"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step7_refuses_when_readable_root_meta_disagrees_with_sniffed_type(self, tmp_path: Path) -> None:
        pdf_bytes = _build_tiny_pdf(b"Mismatched Meta")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes, content_type="text/html")

        with pytest.raises(ReextractionError, match=r"disagrees with the sniffed application/pdf"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step9_refuses_a_lossy_fresh_extraction(self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
        pdf_bytes = _build_tiny_pdf(b"Will Be Monkeypatched Lossy")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)

        class _FailingPage:
            def get(self, key: str, default: object = None) -> object:
                return "/Page" if key == "/Type" else default

            def extract_text(self) -> str:
                raise ValueError("simulated page failure")

        class _OkPage:
            def get(self, key: str, default: object = None) -> object:
                return "/Page" if key == "/Type" else default

            def extract_text(self) -> str:
                return "surviving page text"

        class _FakeReader:
            def __init__(self, _stream: object) -> None:
                self.pages = [_OkPage(), _FailingPage()]

        fake_pypdf = types.ModuleType("pypdf")
        fake_pypdf.PdfReader = _FakeReader  # type: ignore[attr-defined]
        monkeypatch.setitem(sys.modules, "pypdf", fake_pypdf)

        with pytest.raises(ReextractionError, match=r"lossy; refusing to persist"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step9_refuses_a_clean_but_empty_fresh_extraction(self, tmp_path: Path) -> None:
        pdf_bytes = _build_empty_text_pdf()
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)

        with pytest.raises(ReextractionError, match=r"produced empty text; refusing to persist"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step2_refuses_when_artifact_dir_resolves_outside_workspace_root(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Containment defence-in-depth: artifact_dir() is imported from
        carmel.services.evidence, a DIFFERENT module than reextraction.py. The
        raw_sha256 hex-format check (step 1) already prevents traversal for any
        real input, so this guard is unreachable via normal arguments -- it exists
        only to catch a future artifact_dir() that starts returning paths outside
        the workspace root. Exercised here by monkeypatching the NAME AS IMPORTED
        into carmel.services.reextraction (not carmel.services.evidence.artifact_dir
        itself), which is the only way to make that future scenario observable today.
        """
        outside_root = tmp_path.parent / "definitely-outside-the-workspace-root"
        monkeypatch.setattr(reextraction_module, "artifact_dir", lambda root, raw_sha256: outside_root)

        raw_sha256 = "0" * 64
        with pytest.raises(ReextractionError, match=r"refusing to read outside workspace root"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step9_refuses_an_unexpected_extractor_value(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """Reachable for real: when pypdf is not importable, extract.py's
        _extract_pdf returns extractor="pdf:unavailable" instead of raising.
        Forces that branch the same way pypdf-unavailable is forced in production
        -- sys.modules["pypdf"] set to None makes `import pypdf` raise ImportError,
        following the established sys.modules-monkeypatch pattern used by
        test_step9_refuses_a_lossy_fresh_extraction above (which patches in a fake
        module; this patches in an absent one).
        """
        monkeypatch.setitem(sys.modules, "pypdf", None)

        pdf_bytes = _build_tiny_pdf(b"Hello Unavailable")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)

        with pytest.raises(
            ReextractionError, match=r"extractor 'pdf:unavailable', not the expected 'pdf:pypdf'"
        ):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)

    def test_step9_refuses_a_fresh_extraction_with_page_failures(
        self, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
    ) -> None:
        """extract.py's _extract_pdf sets `truncated = truncated or cap_truncated or
        bool(page_failures)` and then `lossy=truncated` -- so ANY genuine PDF parse
        with a non-empty page_failures list is ALSO lossy=True, which means the
        lossy guard (reextraction.py:170) always fires before the page_failures
        guard (reextraction.py:173) could ever be reached through real pypdf
        parsing (see test_step9_refuses_a_lossy_fresh_extraction above, which
        exercises exactly one page failing and lands on the "lossy" message, not a
        page_failures one). Driving the page_failures branch through the genuine
        extraction path is therefore impractical, so -- as the task explicitly
        allows as a fallback -- this test hand-fabricates an ExtractedText with
        page_failures set but lossy=False and monkeypatches extract_text (the name
        as imported into carmel.services.reextraction) to return it, isolating the
        one guard this test targets.
        """
        pdf_bytes = _build_tiny_pdf(b"Hello Partial")
        raw_sha256 = _store_synthetic_artifact(tmp_path, pdf_bytes)

        fabricated = ExtractedText(
            text="surviving page text",
            normalized="surviving page text",
            sections=[],
            extractor="pdf:pypdf",
            lossy=False,
            page_failures=(PageExtractionFailure(page=2, error="simulated page failure"),),
        )
        monkeypatch.setattr(reextraction_module, "extract_text", lambda data, content_type: fabricated)

        with pytest.raises(ReextractionError, match=r"1 page failure\(s\); refusing to persist an incomplete"):
            reextract_artifact(tmp_path, raw_sha256=raw_sha256, max_bytes=MAX_BYTES)
